language: generic
sudo: required
services:
   - docker

before_install:
   - docker build -t bekir/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true bekir/docker-react npm run test -- --coverage
